package conclusion;

public class Conclusion {

	
	/*LOS TRES ALGORITMOS SON DEL MISMO ORDEN DE COMLEJIDAD = N^2
	 *SIN EMBARGO, COMO LAS IDEAS IMPLEMENTADAS SON DISTINTAS, PUEDE SER QUE EN DETERMINADOS CASOS
	 *, UN ALGORITMO TERMINE DE ORDENAR ANTES QUE OTRO.
	 *
	 *OBVIAMENTE, HABRIA QUE MODIFICAR ESTOS ALGORITMOS PARA DARSE CUETA DE ESTO INTERRUMPA LA EJECUCION.
	 */
}
